apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-session-fixes
  namespace: voice-agent-phase5
  labels:
    app: orchestrator-session-fixes
    component: orchestration
    phase: "5"
    version: "5.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-session-fixes
      component: orchestration
  template:
    metadata:
      labels:
        app: orchestrator-session-fixes
        component: orchestration
        phase: "5"
        version: "5.0.1"
    spec:
      containers:
        - name: orchestrator
          image: voice-agent-orchestrator:session-fixes
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: STT_SERVICE_URL
              value: "http://stt-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: TTS_SERVICE_URL
              value: "http://tts-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: LLM_SERVICE_URL
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434"
            - name: LLM_ENDPOINT
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434/api/generate"
            - name: LLM_MODEL_NAME
              value: "qwen3:0.6b"
            - name: REDPANDA_HOST
              value: "redpanda.voice-agent-phase5.svc.cluster.local"
            - name: REDPANDA_PORT
              value: "9092"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-session-fixes
  namespace: voice-agent-phase5
  labels:
    app: orchestrator-session-fixes
    component: orchestration
    phase: "5"
    version: "5.0.1"
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      name: http
  selector:
    app: orchestrator-session-fixes
    component: orchestration
