apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server-session-fixes
  namespace: voice-agent-phase5
  labels:
    app: media-server-session-fixes
    component: media
    phase: "5"
    version: "5.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server-session-fixes
      component: media
  template:
    metadata:
      labels:
        app: media-server-session-fixes
        component: media
        phase: "5"
        version: "5.0.1"
    spec:
      containers:
        - name: media-server
          image: voice-agent-media-server:session-fixes
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: REDPANDA_HOST
              value: "redpanda.voice-agent-phase5.svc.cluster.local"
            - name: REDPANDA_PORT
              value: "9092"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: media-server-session-fixes
  namespace: voice-agent-phase5
  labels:
    app: media-server-session-fixes
    component: media
    phase: "5"
    version: "5.0.1"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: media-server-session-fixes
    component: media
