# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_agent_pb2 as voice__agent__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceAgentServiceStub(object):
    """Voice Agent Service - Direct Communication Protocol
    Replaces Kafka hop with streaming gRPC for lower latency

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/voice_agent.VoiceAgentService/StreamAudio',
                request_serializer=voice__agent__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__agent__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.SendControlMessage = channel.unary_unary(
                '/voice_agent.VoiceAgentService/SendControlMessage',
                request_serializer=voice__agent__pb2.ControlMessage.SerializeToString,
                response_deserializer=voice__agent__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/voice_agent.VoiceAgentService/HealthCheck',
                request_serializer=voice__agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=voice__agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class VoiceAgentServiceServicer(object):
    """Voice Agent Service - Direct Communication Protocol
    Replaces Kafka hop with streaming gRPC for lower latency

    """

    def StreamAudio(self, request_iterator, context):
        """Stream audio from Media Server to Orchestrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControlMessage(self, request, context):
        """Control messages for pipeline management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=voice__agent__pb2.AudioChunk.FromString,
                    response_serializer=voice__agent__pb2.AudioResponse.SerializeToString,
            ),
            'SendControlMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControlMessage,
                    request_deserializer=voice__agent__pb2.ControlMessage.FromString,
                    response_serializer=voice__agent__pb2.ControlResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=voice__agent__pb2.HealthRequest.FromString,
                    response_serializer=voice__agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_agent.VoiceAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_agent.VoiceAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceAgentService(object):
    """Voice Agent Service - Direct Communication Protocol
    Replaces Kafka hop with streaming gRPC for lower latency

    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_agent.VoiceAgentService/StreamAudio',
            voice__agent__pb2.AudioChunk.SerializeToString,
            voice__agent__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControlMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_agent.VoiceAgentService/SendControlMessage',
            voice__agent__pb2.ControlMessage.SerializeToString,
            voice__agent__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_agent.VoiceAgentService/HealthCheck',
            voice__agent__pb2.HealthRequest.SerializeToString,
            voice__agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
