apiVersion: v1
kind: Service
metadata:
  name: voice-ai-backend-v2-service
  labels:
    app: voice-ai-backend-v2
    version: "2.0.0"
    component: webrtc-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: websocket
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: voice-ai-backend-v2
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
# Internal service for cluster communication
apiVersion: v1
kind: Service
metadata:
  name: voice-ai-backend-v2-internal
  labels:
    app: voice-ai-backend-v2
    version: "2.0.0"
    component: webrtc-backend
    type: internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: voice-ai-backend-v2 