apiVersion: v1
kind: Service
metadata:
  name: orchestrator-lb-https
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.0"
spec:
  type: LoadBalancer
  ports:
  - name: websocket-https
    port: 443
    targetPort: 8001
    protocol: TCP
  - name: websocket-http
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: orchestrator
    component: orchestration 