apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.0"
spec:
  type: ClusterIP
  selector:
    app: orchestrator
    component: orchestration
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-lb
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.0"
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      name: websocket
  selector:
    app: orchestrator
    component: orchestration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
      component: orchestration
  template:
    metadata:
      labels:
        app: orchestrator
        component: orchestration
        phase: "5"
        version: "5.0.0"
    spec:
      containers:
        - name: orchestrator
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/orchestrator:v1.0.27
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: STT_SERVICE_URL
              value: "http://stt-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: TTS_SERVICE_URL
              value: "http://tts-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: LLM_SERVICE_URL
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434"
            - name: LLM_ENDPOINT
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434/api/generate"
            - name: LLM_MODEL_NAME
              value: "qwen3:0.6b"
            - name: REDPANDA_HOST
              value: "redpanda.voice-agent-phase5.svc.cluster.local"
            - name: REDPANDA_PORT
              value: "9092"
            - name: SCYLLADB_HOST
              value: "scylladb.voice-agent-phase5.svc.cluster.local"
            - name: SCYLLADB_PORT
              value: "9042"
          # Optimized for free tier
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL 