apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.1"
spec:
  type: ClusterIP
  selector:
    app: orchestrator
    component: orchestration
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: voice-agent-phase5
  labels:
    app: orchestrator
    component: orchestration
    phase: "5"
    version: "5.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
      component: orchestration
  template:
    metadata:
      labels:
        app: orchestrator
        component: orchestration
        phase: "5"
        version: "5.0.1"
    spec:
      containers:
        - name: orchestrator
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/orchestrator:v1.0.26
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: STT_SERVICE_URL
              value: "http://stt-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: TTS_SERVICE_URL
              value: "http://tts-service.voice-agent-phase5.svc.cluster.local:8000"
            - name: LLM_SERVICE_URL
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434"
            - name: LLM_ENDPOINT
              value: "http://llm-service.voice-agent-phase5.svc.cluster.local:11434/api/generate"
            - name: LLM_MODEL_NAME
              value: "qwen3:0.6b"
            - name: REDPANDA_HOST
              value: "redpanda.voice-agent-phase5.svc.cluster.local"
            - name: REDPANDA_PORT
              value: "9092"
            - name: SCYLLADB_HOST
              value: "scylladb.voice-agent-phase5.svc.cluster.local"
            - name: SCYLLADB_PORT
              value: "9042"
          # OPTIMIZED RESOURCES - Based on actual usage analysis
          resources:
            requests:
              cpu: "100m"        # Reduced from 200m (actual usage: 2m)
              memory: "256Mi"    # Reduced from 512Mi (actual usage: 5Mi)
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"        # Reduced from 1 core
              memory: "512Mi"    # Reduced from 1Gi
              ephemeral-storage: "1Gi"
          # THREE-STAGE HEALTH PROBE SYSTEM
          startupProbe:
            httpGet:
              path: /health
              port: 8001
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
---
# Optimized HPA for Orchestrator
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orchestrator-hpa
  namespace: voice-agent-phase5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orchestrator
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30 