apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: voice-agent-phase5
  labels:
    app: redpanda
    component: messaging
    phase: "5"
    version: "5.0.0"
spec:
  type: ClusterIP
  selector:
    app: redpanda
    component: messaging
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
    - protocol: TCP
      port: 9644
      targetPort: 9644
      name: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: voice-agent-phase5
  labels:
    app: redpanda
    component: messaging
    phase: "5"
    version: "5.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
      component: messaging
  template:
    metadata:
      labels:
        app: redpanda
        component: messaging
        phase: "5"
        version: "5.0.0"
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          imagePullPolicy: IfNotPresent
          command:
            - /opt/redpanda/bin/rpk
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - "256M"
            - --node-id
            - "0"
            - --check=false
            - --advertise-kafka-addr
            - "redpanda.voice-agent-phase5.svc.cluster.local:9092"
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
          env:
            - name: REDPANDA_ENABLE_ADMIN_API
              value: "true"
          # Optimized resources - reduced memory
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL 