apiVersion: v1
kind: Service
metadata:
  name: stt-service
  namespace: voice-agent-phase5
  labels:
    app: stt-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  type: ClusterIP
  selector:
    app: stt-service
    component: ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-service
  namespace: voice-agent-phase5
  labels:
    app: stt-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt-service
      component: ai
  template:
    metadata:
      labels:
        app: stt-service
        component: ai
        phase: "5"
        version: "5.0.0"
    spec:
      containers:
        - name: stt-service
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/stt-service:v1.0.16-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: STT_MODEL
              value: "tiny"  # Using tiny model for better performance and lower memory usage
            - name: STT_DEVICE
              value: "cpu"
            - name: TRANSFORMERS_CACHE
              value: "/models"
          # Optimized for ultra-minimal service - light resources
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
              ephemeral-storage: "2Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 60
            timeoutSeconds: 45
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 240
            periodSeconds: 45
            timeoutSeconds: 35
            failureThreshold: 8
          volumeMounts:
            - name: cache-volume
              mountPath: /models
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: cache-volume
          emptyDir: {} 