apiVersion: v1
kind: Service
metadata:
  name: stt-service
  namespace: voice-agent-phase5
  labels:
    app: stt-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  type: ClusterIP
  selector:
    app: stt-service
    component: ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-service
  namespace: voice-agent-phase5
  labels:
    app: stt-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt-service
      component: ai
  template:
    metadata:
      labels:
        app: stt-service
        component: ai
        phase: "5"
        version: "5.0.0"
    spec:
      containers:
        - name: stt-service
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/stt-service:v1.0.14-whisper-large
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: STT_MODEL
              value: "whisper-large"
            - name: STT_DEVICE
              value: "cpu"
            - name: TRANSFORMERS_CACHE
              value: "/models"
          # Increased resources for Whisper Large model
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 300  # Increased for model loading
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 240   # Increased for model loading
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: cache-volume
              mountPath: /models
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: cache-volume
          emptyDir: {} 