apiVersion: v1
kind: Service
metadata:
  name: tts-service
  namespace: voice-agent-phase5
  labels:
    app: tts-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  type: ClusterIP
  selector:
    app: tts-service
    component: ai
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-service
  namespace: voice-agent-phase5
  labels:
    app: tts-service
    component: ai
    phase: "5"
    version: "5.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-service
      component: ai
  template:
    metadata:
      labels:
        app: tts-service
        component: ai
        phase: "5"
        version: "5.0.0"
    spec:
      containers:
        - name: tts-service
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/tts-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: PIPER_MODEL
              value: "en_US-amy-low.onnx"
            - name: PIPER_VOICE
              value: "en_US-amy-low"
            - name: PIPER_DEVICE
              value: "cpu"
          # Optimized for free tier - minimal resources
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL 