apiVersion: v1
kind: Service
metadata:
  name: tts-service
  namespace: voice-agent-phase5
  labels:
    app: tts-service
    component: ai
    phase: "5"
    version: "5.0.1"
spec:
  type: ClusterIP
  selector:
    app: tts-service
    component: ai
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
---
# Persistent Volume Claim for TTS model storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-model-storage-pvc
  namespace: voice-agent-phase5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Space for Piper models
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-service
  namespace: voice-agent-phase5
  labels:
    app: tts-service
    component: ai
    phase: "5"
    version: "5.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-service
      component: ai
  template:
    metadata:
      labels:
        app: tts-service
        component: ai
        phase: "5"
        version: "5.0.1"
    spec:
      containers:
        - name: tts-service
          image: asia-south1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/tts-service:v1.0.0
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: TTS_MODEL_PATH
              value: "/models/en_US-lessac-high.onnx"
            - name: TTS_CONFIG_PATH
              value: "/models/en_US-lessac-high.onnx.json"
          # OPTIMIZED RESOURCES - Based on actual usage analysis
          resources:
            requests:
              cpu: "100m"        # Reduced from 100m (actual usage: 2m)
              memory: "256Mi"    # Reduced from 256Mi (actual usage: 38Mi)
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"        # Reduced from 500m
              memory: "512Mi"    # Reduced from 512Mi
              ephemeral-storage: "1Gi"
          # THREE-STAGE HEALTH PROBE SYSTEM
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: tts-model-storage
              mountPath: /models
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tts-model-storage
          persistentVolumeClaim:
            claimName: tts-model-storage-pvc
---
# HPA for TTS Service (NEW)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tts-service-hpa
  namespace: voice-agent-phase5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tts-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30 