apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: voice-agent-phase3
  labels:
    app: logging-service
    component: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
      component: logging
  template:
    metadata:
      labels:
        app: logging-service
        component: logging
    spec:
      containers:
        - name: logging-service
          image: logging-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SCYLLADB_HOST
              value: "scylladb.voice-agent-phase3.svc.cluster.local"
            - name: SCYLLADB_PORT
              value: "9042"
            - name: SCYLLADB_KEYSPACE
              value: "voice_ai_ks"
            - name: REDPANDA_HOST
              value: "redpanda.voice-agent-phase3.svc.cluster.local"
            - name: REDPANDA_PORT
              value: "9092"
            - name: HTTP_PORT
              value: "8080"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: voice-agent-phase3
  labels:
    app: logging-service
    component: logging
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: logging-service
    component: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-service-config
  namespace: voice-agent-phase3
data:
  log-level: "info"
  metrics-enabled: "true"
  health-check-interval: "30s" 