apiVersion: v1
kind: Service
metadata:
  name: orchestrator-lb
  namespace: voice-agent-fresh
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8001
    targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: media-server-lb
  namespace: voice-agent-fresh
spec:
  selector:
    app: media-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 10000
    targetPort: 10000
    protocol: UDP
    name: rtp
  type: LoadBalancer
