apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server
  namespace: voice-agent-fresh
  labels:
    app: media-server
    version: v2.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
  template:
    metadata:
      labels:
        app: media-server
    spec:
      containers:
      - name: media-server
        image: us-central1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/media-server:v2.0.0
        ports:
        - containerPort: 8001
        env:
        - name: KAFKA_BROKER_HOST
          value: "redpanda.voice-agent-fresh.svc.cluster.local"
        - name: KAFKA_BROKER_PORT
          value: "9092"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: media-server
  namespace: voice-agent-fresh
spec:
  selector:
    app: media-server
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
