apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: voice-agent-fresh
  labels:
    app: orchestrator
    version: v2.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: us-central1-docker.pkg.dev/speechtotext-466820/voice-agent-repo/orchestrator:v2.0.0
        ports:
        - containerPort: 8001
        env:
        - name: ORCHESTRATOR_PORT
          value: "8001"
        - name: KAFKA_ENABLED
          value: "true"
        - name: KAFKA_BROKERS
          value: "redpanda.voice-agent-fresh.svc.cluster.local:9092"
        - name: REDPANDA_HOST
          value: "redpanda.voice-agent-fresh.svc.cluster.local"
        - name: REDPANDA_PORT
          value: "9092"
        - name: ENABLE_HTTPS
          value: "false"
        - name: ENVIRONMENT
          value: "production"
        - name: CORS_ALLOWED_ORIGINS
          value: "https://dharsan-voice-agent-frontend.vercel.app,https://voice-agent-frontend.vercel.app,https://groundedai.in,https://*.groundedai.in"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: voice-agent-fresh
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP 