apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stt-model-storage-pvc
  namespace: voice-agent-fresh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-model-storage-pvc
  namespace: voice-agent-fresh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-storage-pvc
  namespace: voice-agent-fresh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
