// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/voice_agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response types
type ResponseType int32

const (
	ResponseType_RESPONSE_TYPE_UNSPECIFIED        ResponseType = 0
	ResponseType_RESPONSE_TYPE_TTS_AUDIO          ResponseType = 1
	ResponseType_RESPONSE_TYPE_INTERIM_TRANSCRIPT ResponseType = 2
	ResponseType_RESPONSE_TYPE_FINAL_TRANSCRIPT   ResponseType = 3
	ResponseType_RESPONSE_TYPE_AI_RESPONSE        ResponseType = 4
	ResponseType_RESPONSE_TYPE_ERROR              ResponseType = 5
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "RESPONSE_TYPE_UNSPECIFIED",
		1: "RESPONSE_TYPE_TTS_AUDIO",
		2: "RESPONSE_TYPE_INTERIM_TRANSCRIPT",
		3: "RESPONSE_TYPE_FINAL_TRANSCRIPT",
		4: "RESPONSE_TYPE_AI_RESPONSE",
		5: "RESPONSE_TYPE_ERROR",
	}
	ResponseType_value = map[string]int32{
		"RESPONSE_TYPE_UNSPECIFIED":        0,
		"RESPONSE_TYPE_TTS_AUDIO":          1,
		"RESPONSE_TYPE_INTERIM_TRANSCRIPT": 2,
		"RESPONSE_TYPE_FINAL_TRANSCRIPT":   3,
		"RESPONSE_TYPE_AI_RESPONSE":        4,
		"RESPONSE_TYPE_ERROR":              5,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_voice_agent_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_proto_voice_agent_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{0}
}

// Control types
type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNSPECIFIED     ControlType = 0
	ControlType_CONTROL_TYPE_START_LISTENING ControlType = 1
	ControlType_CONTROL_TYPE_STOP_LISTENING  ControlType = 2
	ControlType_CONTROL_TYPE_TRIGGER_LLM     ControlType = 3
	ControlType_CONTROL_TYPE_RESET_SESSION   ControlType = 4
	ControlType_CONTROL_TYPE_PAUSE_PIPELINE  ControlType = 5
	ControlType_CONTROL_TYPE_RESUME_PIPELINE ControlType = 6
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0: "CONTROL_TYPE_UNSPECIFIED",
		1: "CONTROL_TYPE_START_LISTENING",
		2: "CONTROL_TYPE_STOP_LISTENING",
		3: "CONTROL_TYPE_TRIGGER_LLM",
		4: "CONTROL_TYPE_RESET_SESSION",
		5: "CONTROL_TYPE_PAUSE_PIPELINE",
		6: "CONTROL_TYPE_RESUME_PIPELINE",
	}
	ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNSPECIFIED":     0,
		"CONTROL_TYPE_START_LISTENING": 1,
		"CONTROL_TYPE_STOP_LISTENING":  2,
		"CONTROL_TYPE_TRIGGER_LLM":     3,
		"CONTROL_TYPE_RESET_SESSION":   4,
		"CONTROL_TYPE_PAUSE_PIPELINE":  5,
		"CONTROL_TYPE_RESUME_PIPELINE": 6,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_voice_agent_proto_enumTypes[1].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_proto_voice_agent_proto_enumTypes[1]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{1}
}

// Audio chunk from Media Server to Orchestrator
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *AudioMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_voice_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioChunk) GetMetadata() *AudioMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Audio metadata for processing
type AudioMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyLevel   float32                `protobuf:"fixed32,1,opt,name=energy_level,json=energyLevel,proto3" json:"energy_level,omitempty"`
	VoiceActivity bool                   `protobuf:"varint,2,opt,name=voice_activity,json=voiceActivity,proto3" json:"voice_activity,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AudioFormat   string                 `protobuf:"bytes,4,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"` // e.g., "opus", "pcm"
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMetadata) Reset() {
	*x = AudioMetadata{}
	mi := &file_proto_voice_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMetadata) ProtoMessage() {}

func (x *AudioMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMetadata.ProtoReflect.Descriptor instead.
func (*AudioMetadata) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AudioMetadata) GetEnergyLevel() float32 {
	if x != nil {
		return x.EnergyLevel
	}
	return 0
}

func (x *AudioMetadata) GetVoiceActivity() bool {
	if x != nil {
		return x.VoiceActivity
	}
	return false
}

func (x *AudioMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AudioMetadata) GetAudioFormat() string {
	if x != nil {
		return x.AudioFormat
	}
	return ""
}

func (x *AudioMetadata) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioMetadata) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// Audio response from Orchestrator to Media Server
type AudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResponseType  ResponseType           `protobuf:"varint,4,opt,name=response_type,json=responseType,proto3,enum=voice_agent.ResponseType" json:"response_type,omitempty"`
	Transcript    string                 `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"`
	AiResponse    string                 `protobuf:"bytes,6,opt,name=ai_response,json=aiResponse,proto3" json:"ai_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioResponse) Reset() {
	*x = AudioResponse{}
	mi := &file_proto_voice_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResponse) ProtoMessage() {}

func (x *AudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResponse.ProtoReflect.Descriptor instead.
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AudioResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioResponse) GetResponseType() ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return ResponseType_RESPONSE_TYPE_UNSPECIFIED
}

func (x *AudioResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *AudioResponse) GetAiResponse() string {
	if x != nil {
		return x.AiResponse
	}
	return ""
}

// Control message for pipeline management
type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ControlType   ControlType            `protobuf:"varint,2,opt,name=control_type,json=controlType,proto3,enum=voice_agent.ControlType" json:"control_type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_voice_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlMessage) GetControlType() ControlType {
	if x != nil {
		return x.ControlType
	}
	return ControlType_CONTROL_TYPE_UNSPECIFIED
}

func (x *ControlMessage) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ControlMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Control response
type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_proto_voice_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ControlResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Health check request
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_voice_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_voice_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_voice_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_voice_agent_proto protoreflect.FileDescriptor

const file_proto_voice_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/voice_agent.proto\x12\vvoice_agent\"\xa0\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x126\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1a.voice_agent.AudioMetadataR\bmetadata\"\xd9\x01\n" +
	"\rAudioMetadata\x12!\n" +
	"\fenergy_level\x18\x01 \x01(\x02R\venergyLevel\x12%\n" +
	"\x0evoice_activity\x18\x02 \x01(\bR\rvoiceActivity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\faudio_format\x18\x04 \x01(\tR\vaudioFormat\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x05R\bchannels\"\xec\x01\n" +
	"\rAudioResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12>\n" +
	"\rresponse_type\x18\x04 \x01(\x0e2\x19.voice_agent.ResponseTypeR\fresponseType\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\x12\x1f\n" +
	"\vai_response\x18\x06 \x01(\tR\n" +
	"aiResponse\"\x96\x02\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\fcontrol_type\x18\x02 \x01(\x0e2\x18.voice_agent.ControlTypeR\vcontrolType\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.voice_agent.ControlMessage.ParametersEntryR\n" +
	"parameters\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x0fControlResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"P\n" +
	"\rHealthRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x87\x02\n" +
	"\x0eHealthResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).voice_agent.HealthResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xcc\x01\n" +
	"\fResponseType\x12\x1d\n" +
	"\x19RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESPONSE_TYPE_TTS_AUDIO\x10\x01\x12$\n" +
	" RESPONSE_TYPE_INTERIM_TRANSCRIPT\x10\x02\x12\"\n" +
	"\x1eRESPONSE_TYPE_FINAL_TRANSCRIPT\x10\x03\x12\x1d\n" +
	"\x19RESPONSE_TYPE_AI_RESPONSE\x10\x04\x12\x17\n" +
	"\x13RESPONSE_TYPE_ERROR\x10\x05*\xef\x01\n" +
	"\vControlType\x12\x1c\n" +
	"\x18CONTROL_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONTROL_TYPE_START_LISTENING\x10\x01\x12\x1f\n" +
	"\x1bCONTROL_TYPE_STOP_LISTENING\x10\x02\x12\x1c\n" +
	"\x18CONTROL_TYPE_TRIGGER_LLM\x10\x03\x12\x1e\n" +
	"\x1aCONTROL_TYPE_RESET_SESSION\x10\x04\x12\x1f\n" +
	"\x1bCONTROL_TYPE_PAUSE_PIPELINE\x10\x05\x12 \n" +
	"\x1cCONTROL_TYPE_RESUME_PIPELINE\x10\x062\xf4\x01\n" +
	"\x11VoiceAgentService\x12F\n" +
	"\vStreamAudio\x12\x17.voice_agent.AudioChunk\x1a\x1a.voice_agent.AudioResponse(\x010\x01\x12O\n" +
	"\x12SendControlMessage\x12\x1b.voice_agent.ControlMessage\x1a\x1c.voice_agent.ControlResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.voice_agent.HealthRequest\x1a\x1b.voice_agent.HealthResponseB\x13Z\x11voice-agent/protob\x06proto3"

var (
	file_proto_voice_agent_proto_rawDescOnce sync.Once
	file_proto_voice_agent_proto_rawDescData []byte
)

func file_proto_voice_agent_proto_rawDescGZIP() []byte {
	file_proto_voice_agent_proto_rawDescOnce.Do(func() {
		file_proto_voice_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_voice_agent_proto_rawDesc), len(file_proto_voice_agent_proto_rawDesc)))
	})
	return file_proto_voice_agent_proto_rawDescData
}

var file_proto_voice_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_voice_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_voice_agent_proto_goTypes = []any{
	(ResponseType)(0),       // 0: voice_agent.ResponseType
	(ControlType)(0),        // 1: voice_agent.ControlType
	(*AudioChunk)(nil),      // 2: voice_agent.AudioChunk
	(*AudioMetadata)(nil),   // 3: voice_agent.AudioMetadata
	(*AudioResponse)(nil),   // 4: voice_agent.AudioResponse
	(*ControlMessage)(nil),  // 5: voice_agent.ControlMessage
	(*ControlResponse)(nil), // 6: voice_agent.ControlResponse
	(*HealthRequest)(nil),   // 7: voice_agent.HealthRequest
	(*HealthResponse)(nil),  // 8: voice_agent.HealthResponse
	nil,                     // 9: voice_agent.ControlMessage.ParametersEntry
	nil,                     // 10: voice_agent.HealthResponse.MetadataEntry
}
var file_proto_voice_agent_proto_depIdxs = []int32{
	3,  // 0: voice_agent.AudioChunk.metadata:type_name -> voice_agent.AudioMetadata
	0,  // 1: voice_agent.AudioResponse.response_type:type_name -> voice_agent.ResponseType
	1,  // 2: voice_agent.ControlMessage.control_type:type_name -> voice_agent.ControlType
	9,  // 3: voice_agent.ControlMessage.parameters:type_name -> voice_agent.ControlMessage.ParametersEntry
	10, // 4: voice_agent.HealthResponse.metadata:type_name -> voice_agent.HealthResponse.MetadataEntry
	2,  // 5: voice_agent.VoiceAgentService.StreamAudio:input_type -> voice_agent.AudioChunk
	5,  // 6: voice_agent.VoiceAgentService.SendControlMessage:input_type -> voice_agent.ControlMessage
	7,  // 7: voice_agent.VoiceAgentService.HealthCheck:input_type -> voice_agent.HealthRequest
	4,  // 8: voice_agent.VoiceAgentService.StreamAudio:output_type -> voice_agent.AudioResponse
	6,  // 9: voice_agent.VoiceAgentService.SendControlMessage:output_type -> voice_agent.ControlResponse
	8,  // 10: voice_agent.VoiceAgentService.HealthCheck:output_type -> voice_agent.HealthResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_voice_agent_proto_init() }
func file_proto_voice_agent_proto_init() {
	if File_proto_voice_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_voice_agent_proto_rawDesc), len(file_proto_voice_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_voice_agent_proto_goTypes,
		DependencyIndexes: file_proto_voice_agent_proto_depIdxs,
		EnumInfos:         file_proto_voice_agent_proto_enumTypes,
		MessageInfos:      file_proto_voice_agent_proto_msgTypes,
	}.Build()
	File_proto_voice_agent_proto = out.File
	file_proto_voice_agent_proto_goTypes = nil
	file_proto_voice_agent_proto_depIdxs = nil
}
